### ISSUE TITLE
Trained Model

### ISSUE THREAD

**Issue by sivaram1207** [hengluchang/deep-news-summarization#2]
Hi, Thanks for the repo. Is it possible for you to share the model that was trained on gigaword dataset.

**Comment by hengluchang** [comment]
Thanks for your interest in the repo! I have pushed a python script to download model parameters which was trained on a larger portion of Gigaword (10 years of Associated Press Worldstream). Please check the **Download vocabs and trained model parameters** section in the readme for more details.

**Comment by sivaram1207** [comment]
Thank you. Much appreciated
